name: Android CI

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle'
    branches-ignore:
      - 'wip/**'
  workflow_dispatch:

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.set_sha.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Set short SHA
        id: set_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Rename APK with commit hash
        run: |
          mv app/build/outputs/apk/release/app-release.apk \
             app/build/outputs/apk/release/app-release-${{ steps.set_sha.outputs.short_sha }}.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release-${{ steps.set_sha.outputs.short_sha }}
          path: app/build/outputs/apk/release/app-release-${{ steps.set_sha.outputs.short_sha }}.apk